### Healthcheck
GET http://127.0.0.1:80/api/trains/health/
Accept: application/json

### Version
GET http://127.0.0.1:80/api/trains/version/
Accept: application/json

### List Train Schedules
GET http://127.0.0.1:80/api/trains/
Accept: application/json

### Create Train Schedule
POST http://127.0.0.1:80/api/trains/
Content-Type: application/json

{
    "train_number": "WAW-GDA",
    "departure_time": "2026-11-05T10:00:00+00:00",
    "arrival_time": "2026-11-06T14:00:00+00:00",
    "max_seats": "200",
    "version": "1"
}

### Update Train Schedule
PUT http://127.0.0.1:80/api/trains/
Content-Type: application/json

{
    "train_number": "1234567",
    "departure_time": "2025-11-03T10:00:00+00:00",
    "arrival_time": "2026-11-04T14:00:00+00:00",
    "old_departure_time": "2025-11-03T10:00:00+00:00",
    "old_arrival_time": "2026-11-04T14:00:00+00:00"
}