version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/build:/usr/share/nginx/html

  user:
    build:
      context: ./Backend/User/
    command: sh -c "python manage.py collectstatic --noinput && gunicorn User.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./Backend/User/.env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./Postgres/.env.dev
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    env_file:
      - ./PgAdmin/.env.dev
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./RabbitMQ/.env.dev

volumes:
  postgres_data:
  pgadmin_data:
  static_volume:
