version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend/
    volumes:
      - ./Frontend/build:/usr/share/nginx/html

  user:
    build:
      context: ./Backend/User/
    command: sh -c "python manage.py collectstatic --noinput && gunicorn User.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./Backend/User/.env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db_user
      - rabbitmq

  db_user:
    image: postgres:16
    volumes:
      - db_user_data:/var/lib/postgresql/data
    env_file:
      - ./PostgresUser/.env.dev
    ports:
      - "5432:5432"
      
  train:
    build:
      context: ./Backend/train/
    command: sh -c "python manage.py collectstatic --noinput && gunicorn train.wsgi:application --bind 0.0.0.0:8001"
    env_file:
      - ./Backend/train/.env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      rabbitmq:
        condition: service_healthy
      eventstore:
        condition: service_started
      db_train:
        condition: service_started

  db_train:
    image: postgres:16
    volumes:
      - db_train_data:/var/lib/postgresql/data
    env_file:
      - ./PostgresTrain/.env.dev      
    ports:
      - "5433:5432"
        
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    env_file:
      - ./PgAdmin/.env.dev
    depends_on:
      - db_user
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user
      - train

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./RabbitMQ/.env.dev
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      
  eventstore:
    image: eventstore/eventstore:24.6
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  db_user_data:
  pgadmin_data:
  static_volume:
  eventstore-volume-data:
  eventstore-volume-logs:
  db_train_data: